import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/NavBar/NavBar";

export const metadata: Metadata = {
  title: "Fetching API",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
      </head>
      <body >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
